

Vagrant.configure("2") do |config|

  config.vm.box_download_insecure=true
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end
  config.vm.define "ci-server" do |ciServer|
    ciServer.vm.network "private_network", ip:'192.168.56.60'
    ciServer.vm.hostname = "ci-server"
    ciServer.vm.provision :docker
    ciServer.vm.provision :docker_compose
    ciServer.vm.provision :file, source:"../docker/docker-compose.ci.yml", destination:"docker-compose.yml"
    ciServer.vm.provision :shell, inline: "sudo chmod 777 /var/run/docker.sock"
    ciServer.vm.provision :docker_compose, yml:"/home/vagrant/docker-compose.yml", run: "always"
  end

  config.vm.define "ci-server2" do |ciServer2|
    ciServer2.vm.network "private_network", ip:'192.168.56.70'
    ciServer2.vm.hostname = "ci-server2"
    ciServer2.vm.provision :docker
  end

  config.vm.define "cd-server" do |cd|
    cd.vm.network "private_network", ip:'192.168.56.80'
    cd.vm.hostname = "cd-server"
    cd.vm.provision :docker
    cd.vm.provision :file, source:"../docker/docker-compose.cd.yml", destination:"docker-compose.yml"
    cd.vm.provision :shell, inline: "sudo chmod 777 /var/run/docker.sock"
    cd.vm.provision :docker_compose, yml:"/home/vagrant/docker-compose.yml", run: "always"
  end
end
