
$script = <<-SCRIPT
echo "I like Vagrant"
echo "I love Linux"
date > ~/vagrant_provisioned_at
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.box_download_insecure=true
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  config.vm.define "ci-server" do |ciServer|
    ciServer.vm.network "private_network", ip:'192.168.56.60'
    ciServer.vm.hostname = "ci-server"
    ciServer.vm.provision :docker
    ciServer.vm.provision :docker_compose
    ciServer.vm.provision :file, source:"../docker/docker-compose.ci.yml", destination:"docker-compose.yml"
    ciServer.vm.provision :docker_compose, yml:"/home/vagrant/docker-compose.yml", run: "always"
  end


end
